import React from "react";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import checkmk from "../../public/cm.png";
import mockup from "../../public/mobile-mockup.png";
import wave from "../../public/wave.svg";
import steps from "../../public/howItWorks.png";
export default function Home() {
	const [generatedCode, setGeneratedCode] = useState('');
	const [enteredCode, setEnteredCode] = useState('');
	const [message, setMessage] = useState('');
	const [error, setError] = useState('');
	const generateCode = async () => {
		try {
		  const response = await fetch('http://localhost:8000/api/codes');
		  const data = await response.json();
		  setGeneratedCode(data.code);
		  setMessage('');
		  setError('');
		} catch (error) {
		  setError('Error generating code');
		}
	  };
	
	  const submitCode = async () => {
		try {
		  const response = await fetch('http://localhost:8000/api/codes/use', {
			method: 'POST',
			headers: {
			  'Content-Type': 'application/json',
			},
			
			body: JSON.stringify({ code: enteredCode }),
		  });
	
		  const data = await response.json();
		  if(data.success){
			setMessage(data.message);
		  }
		  else{
			  setError(data.message);
		  }
		} catch (error) {
		  console.error(error)
		}
	  };
	return (
		<>
			<Head>
				<title>Weathup</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="container1">
					<div className="heading"> Check your financial health</div>
					<div className="subHeading">
						Use WeathoMeter to get a free report card for your
						finances - within minutes!
					</div>
					<button className="getStartedBtn"> Get Started</button>
					<div className="bullets-container">
						<div className="left-bullets">
							<div className="bullet">
								<Image src={checkmk} />
								<p className="underlined-text">
									Expected Retirement Age
								</p>
							</div>
							<div className="bullet">
								<Image src={checkmk} />
								<p className="underlined-text">
									Identify Mistakes
								</p>
							</div>
						</div>

						<div className="center-image">
							<Image src={mockup} />
						</div>

						<div className="right-bullets">
							<div className="bullet">
								<Image src={checkmk} />
								<p className="underlined-text">
									Personalised Road Map
								</p>
							</div>
							<div className="bullet">
								<Image src={checkmk} />
								<p className="underlined-text">
									Tips To Improve
								</p>
							</div>
						</div>
					</div>
					<div className="container3">
						<div className="container3-heading">How it works?</div>
						{/* <div className="wave">
							<Image src={wave} />
						</div> */}
						<div className="container3-steps">
							<Image className="steps-img" src={steps} />
						</div>
						<div className="three-steps">
							<div className="left-div">
								<p>Answer few questions</p>
							</div>

							<div className="center-div">
								<p>Register using phone and OTP</p>
							</div>

							<div className="right-div">
								<p>Get report and personal roadmapt</p>
							</div>
						</div>
						<div className="container3-button">
							<button className="getStartedBtn">
								{" "}
								Get Started
							</button>
						</div>
					</div>
					<div>
      <div>
        <p>Generated Code: {generatedCode}</p>
        <button onClick={generateCode}>Refresh</button>
      </div>

      <div>
        <input
          type="text"
          placeholder="Enter code"
          value={enteredCode}
          onChange={(e) => setEnteredCode(e.target.value)}
        />
        <button onClick={submitCode}>Submit</button>
      </div>

      {message && <p style={{ color: 'green' }}>{message}</p>}
      {error && <p style={{ color: 'red' }}>{error}</p>}
    </div>
				</div>
			</main>
		</>
	);
}
